[package]
name = "maelstrom"
version = "0.1.0"
authors = ["Andrew Halle <me@andrewhalle.dev>"]
edition = "2021"

[dependencies]
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
