[package]
name = "unique-ids"
version = "0.1.0"
authors = ["Andrew Halle me@andrewhalle.dev"]
edition = "2021"

[dependencies]
maelstrom = { version = "0.1.0", path = "../maelstrom" }
serde_json = "1.0.105"
uuid = { version = "1.4.1", features = ["v4"] }
