[package]
name = "echo"
version = "0.1.0"
authors = ["Andrew Halle <me@andrewhalle.dev>"]
edition = "2021"

[dependencies]
maelstrom = { version = "0.1.0", path = "../maelstrom" }
serde_json = "1.0.105"
